## Section: Core config
homeassistant:
  # Name of the location where Home Assistant is running
  name: Taylor Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.7.173
      allow_bypass_login: true

http:
cloud:
airvisual:
  api_key: !secret airvisual_api_key
  geographies:
      city: Berkeley
      state: California
      country: USA

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
lovelace:
  mode: yaml
  resources:
    - type: module
      url: /hacsfiles/custom-header/custom-header.js
    - type: module
      url: /hacsfiles/button-card/button-card.js
    - type: module
      url: /hacsfiles/lovelace-card-mod/card-mod.js
    - type: js
      url: /hacsfiles/light-entity-card/light-entity-card.js
    - type: js
      url: /hacsfiles/rgb-light-card/card.js
    - type: module
      url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    - type: module
      url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    - type: module
      url: /hacsfiles/simple-thermostat/simple-thermostat.js
    - type: module
      url: /hacsfiles/button-toolbar/button-toolbar.js
    - type: module
      url: /local/community/button-toolbar-redux/button-toolbar.js
    - type: module
      url: /local/community/calendar_notification/calendar_notification.js
    # - type: module
    #   url: /local/community/custom_notifications/custom-header.js
  # Add more dashboards
  dashboards:
    lovelace-main:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Main
      icon: mdi:tools
      show_in_sidebar: false
      require_admin: false
    mobile-main:
      mode: yaml
      filename: mobile-lovelace.yaml
      title: Mobile
      icon: mdi:cellphone-iphone
      show_in_sidebar: true
      require_admin: false


# Enables configuration UI
config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
# logbook:

mobile_app:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

device_tracker:
  - platform: eero_tracker
    consider_home: 300
    new_device_defaults:
        track_new_devices: true
    interval_seconds: 60 # Recommended...do not set this lower than 25, we don't want to DDOS Eero
    # only_macs: "11:22:33:44:55:66, 22:22:22:22:22:22"  # Optional
  - platform: bluetooth_tracker

person:
  - name: Joe
    id: joe
    device_trackers:
      - device_tracker.joe_s_iphone_11
      - device_tracker.joes_iphone
  - name: Kim
    id: kim
    device_trackers:
      - device_tracker.kim_s_iphone_x
      - device_tracker.meow

dyson:
  language: US
  username: !secret dyson_username
  password: !secret dyson_password
  devices:
    - device_id: !secret dyson_device_id
      device_ip: !secret dyson_device_ip

# Simple Service Discovery Protocol
ssdp:

# Track the sun
sun:

system_health:

# Checks for available updates
updater:
  include_used_components: true

## Section: Integration Config

ios:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

homekit:
  auto_start: false

## Section: Component configuration

group: !include groups.yaml

light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.living_room_left
      - light.living_room_middle_left
      - light.living_room_middle_right
      - light.living_room_right
      - light.tripod_lamp

# tuya:
#   username: !secret tuya_un
#   password: !secret tuya_pw
#   country_code: 1

# apple_tv:
#   - host: 192.168.7.29
#     login_id: !secret apple_tv_login_id
#     name: Apple TV

# Discover some devices automatically
discovery:
  ignore:

sensor: !include sensor.yaml

binary_sensor: !include binary_sensors.yaml

