custom_header:
  active_tab_color: var(--state-icon-active-color)
  background: var(--app-header-background-color)
  compact_mode: true
  elements_color: var(--app-header-text-color)
  tab_indicator_color: var(--state-icon-active-color)

title: Mobile
views:
  - panel: true
    icon: 'mdi:home'
    path: mobile
    theme: Google Dark Theme
    title: Mobile
    cards:
      # Main Single Full Width Column
      - type: vertical-stack
        cards:

          - type: "custom:calendar-notification"
            entities:
              - entity: calendar.street_sweeping_ours
                color: red
              - entity: calendar.street_sweeping_theirs
                color: red

          - type: vertical-stack
            cards: !include ui/column_1.yaml


          # Column Two
          - type: vertical-stack
            cards: !include ui/column_2.yaml


          # Column Three
          - type: vertical-stack
            cards: !include ui/column_3.yaml


          # Column Four
          - type: vertical-stack
            cards: !include ui/column_4.yaml

  - panel: true
    icon: 'mdi:leaf'
    path: water
    theme: Google Dark Theme
    title: Yard
    cards: !include ui/yard.yaml

  - panel: true
    icon: 'mdi:beach'
    path: vacation
    theme: Google Dark Theme
    title: Vacation Mode
    cards: !include ui/vacation.yaml


