custom_header:
  active_tab_color: var(--state-icon-active-color)
  background: var(--app-header-background-color)
  compact_mode: true
  elements_color: var(--app-header-text-color)
  tab_indicator_color: var(--state-icon-active-color)

title: Home
views:
  - cards:
      # Main Single Full Width Column
      - type: vertical-stack
        cards:

          - type: "custom:calendar-notification"
            title: "Calendar"
            entities:
            - entity: calendar.street_sweeping_ours
              color: red

          # Three Columns
          - type: horizontal-stack
            cards:

            # Column One
            - type: vertical-stack
              cards:

              - type: horizontal-stack
                cards:
                  - entities:
                      - entity: sensor.dyson_temperature
                        name: Living Room
                        show_legend: false
                        color: '#e74c3c'
                      - entity: sensor.master_room_temperature
                        name: Bedroom Room
                        show_legend: false
                        color: '#EC6653'
                      - entity: sensor.dining_room_temperature
                        name: Dining Room
                        show_legend: false
                        color: '#F1806B'
                      - entity: sensor.bella_room_temperature
                        name: Bella's Room
                        show_legend: false
                        color: '#EE735F'
                    font_size: 75
                    line_color: '#e74c3c'
                    line_width: 2
                    name: Temp
                    type: 'custom:mini-graph-card'

              - type: horizontal-stack
                cards:
                  - entities:
                      - entity: sensor.dyson_humidity
                        name: Living Room
                        show_legend: false
                        color: '#66C1E2'
                      - entity: sensor.master_room_humidity
                        name: Bedroom Room
                        show_legend: false
                        color: '#46AEDD'
                      - entity: sensor.dining_room_humidity
                        name: Dining Room
                        show_legend: false
                        color: '#3498DB'
                      - entity: sensor.bella_room_humidity
                        name: Bella's Room
                        show_legend: false
                        color: '#2D84BE'
                    font_size: 75
                    icon: 'mdi:water-percent'
                    line_color: var(--accent-color)
                    line_width: 2
                    name: Humidity
                    type: 'custom:mini-graph-card'

              - type: horizontal-stack
                cards:
                  - entities:
                      - entity: sensor.steps
                        index: 0
                    font_size: 75
                    line_color: var(--accent-color)
                    line_width: 8
                    name: Joe's Steps
                    type: 'custom:mini-graph-card'
                  - entities:
                      - entity: sensor.steps_3
                        index: 0
                    font_size: 75
                    line_color: '#e74c3c'
                    line_width: 8
                    name: Kim's Steps
                    type: 'custom:mini-graph-card'
                  - entities:
                      - entity: sensor.dyson_aqi
                        index: 0
                    font_size: 75
                    icon: 'mdi:chart-line'
                    line_color: green
                    line_width: 8
                    name: AQI
                    type: 'custom:mini-graph-card'


            # Column Two
            - type: vertical-stack
              cards:

                - control:
                    hvac:
                      fan_only: false
                      cool: false
                      heat_cool: false
                      auto: false
                      dry: false
                      heat: true
                      'off': true
                  entity: climate.zen_thermostat
                  hide:
                    temperature: true
                  name: false
                  fallback: 00.0
                  step_size: 1
                  style: |
                    ha-card {
                      --st-mode-background: var(--paper-card-background-color);
                      --st-mode-active-background: var(--paper-card-background-color);
                      --sidebar-selected-icon-color: var(--accent-color);
                      --st-spacing: 4px;
                      --st-font-size-m: 15px
                      --st-font-size-xl: 40px;
                      }
                  type: 'custom:simple-thermostat'

                - type: entities
                  entities:
                    - entity: fan.living_room
                      hide_when_off: true
                      name: Dyson
                      toggle: true
                      type: 'custom:slider-entity-row'
                    - type: 'custom:button-toolbar-redux'
                      style: |
                        ha-card {
                          --bt-toolbar-background: var(--paper-card-background-color);
                          --bt-icon-active-color: var(--accent-color)
                          }
                      toolbar:
                        - type: service
                          name: Toggle
                          icon: mdi:refresh
                          service:
                            name: fan.oscillate
                            entity: fan.living_room
                            parameter: oscillating
                            toggle: true
                        - type: service
                          name: Auto
                          icon: mdi:auto-fix
                          service:
                            name: dyson.set_auto_mode
                            entity: fan.living_room
                            parameter: auto_mode
                            toggle: true
                        - type: service
                          name: Toggle
                          icon: mdi:weather-night
                          service:
                            name: dyson.set_night_mode
                            entity: fan.living_room
                            parameter: night_mode
                            toggle: true

                - type: entities
                  entities:
                    - entity: device_tracker.joe_tracker_presence
                    - entity: device_tracker.kim_tracker_presence
                  show_header_toggle: false
                  title: Home

            # Column Three
            - type: vertical-stack
              cards:

                - type: horizontal-stack
                  cards:
                    - entities:
                        - entity: sensor.pi_temperature
                          index: 0
                      font_size: 75
                      hours_to_show: 3
                      line_color: green
                      line_width: 8
                      name: π Temp
                      points_per_hour: 10
                      symbol: Mb/s
                      type: 'custom:mini-graph-card'
                    - entities:
                        - entity: sensor.processor_use
                          index: 0
                      font_size: 75
                      hours_to_show: 3
                      line_color: orange
                      line_width: 8
                      name: π CPU
                      points_per_hour: 10
                      type: 'custom:mini-graph-card'

                - show_header_toggle: false
                  entities:
                    - entity: light.living_room
                      hide_when_off: true
                      name: Living room
                      toggle: true
                      type: 'custom:slider-entity-row'
                    - entity: light.living_room
                      hide_when_off: true
                      toggle: false
                      full_row: true
                      hide_state: true
                      attribute: color_temp
                      type: 'custom:slider-entity-row'
                    - colors:
                        - brightness: 0
                          icon_color: '#222'
                        - brightness: 128
                          icon_color: '#ff8'
                        - brightness: 255
                          icon_color: '#ffa'
                        - color_temp: 160
                          icon_color: '#ffead9'
                        - color_temp: 350
                          icon_color: '#ffa859'
                        - color_temp: 550
                          icon_color: '#ff8000'
                      entity: light.living_room
                      justify: between
                      size: 36
                      type: 'custom:rgb-light-card'
                    - entity: light.hall
                      hide_when_off: true
                      name: Hall
                      toggle: true
                      type: 'custom:slider-entity-row'
                    - entity: light.hall
                      hide_when_off: true
                      toggle: false
                      full_row: true
                      hide_state: true
                      attribute: hue
                      type: 'custom:slider-entity-row'
                    - colors:
                        - brightness: 0
                          icon_color: '#222'
                        - rgb_color:
                            - 241
                            - 224
                            - 181
                        - rgb_color:
                            - 239
                            - 210
                            - 117
                        - rgb_color:
                            - 245
                            - 250
                            - 246
                        - icon_color: '#D72AE0'
                          rgb_color:
                            - 255
                            - 127
                            - 255
                        - icon_color: '#E02A2A'
                          rgb_color:
                            - 255
                            - 0
                            - 0
                      entity: light.hall
                      justify: between
                      size: 36
                      type: 'custom:rgb-light-card'
                  type: entities

            # Column Four
            - type: vertical-stack
              cards:

                - type: entities
                  entities:
                    - entity: binary_sensor.front_door_status_sensor
                    - entity: binary_sensor.back_door_status_sensor
                    - entity: binary_sensor.studio_door_status_sensor
                    - entity: light.flood_light

                - type: entities
                  show_header_toggle: false
                  entities:
                    - group.power_bar
                    - switch.power_computer


    panel: true
    icon: 'mdi:home'
    path: home
    theme: Google Dark Theme
    title: New Home

