custom_header:
  active_tab_color: var(--state-icon-active-color)
  background: var(--app-header-background-color)
  compact_mode: true
  elements_color: var(--app-header-text-color)
  tab_indicator_color: var(--state-icon-active-color)

title: Home
views:
  - panel: true
    icon: 'mdi:skull-outline'
    path: home
    theme: Google Dark Theme
    title: Home
    cards:
      # Main Single Full Width Column
      - type: vertical-stack
        cards:

          - type: "custom:calendar-notification"
            entities:
              - entity: calendar.street_sweeping_ours
                color: red
              - entity: calendar.street_sweeping_theirs
                color: red

          # Three Columns
          - type: horizontal-stack
            cards:

            # Column One
            - type: vertical-stack
              cards: !include ui/column_1.yaml


            # Column Two
            - type: vertical-stack
              cards: !include ui/column_2.yaml


            # Column Three
            - type: vertical-stack
              cards: !include ui/column_3.yaml


            # Column Four
            - type: vertical-stack
              cards: !include ui/column_4.yaml


  - panel: false
    icon: 'mdi:leaf'
    path: water
    theme: Google Dark Theme
    title: Yard
    cards:
      - type: entities
        title: Info
        show_header_toggle: false
        entities:
          - entity: sensor.sprinkler_status
          - entity: sensor.sprinkler_last_run
            icon: mdi:calendar-arrow-left
          - entity: sensor.sprinkler_next_run
            icon: mdi:calendar-arrow-right
      - type: entities
        show_header_toggle: false
        entities:
          - entity: switch.sonoff_4ch_relay_1
            name: Top Flat
          - entity: switch.sonoff_4ch_relay_2
            name: Raised Bed
          - entity: switch.sonoff_4ch_relay_3
            name: Slope
          - entity: switch.sonoff_4ch_relay_4
            name: Street
          - entity: binary_sensor.sonoff_4ch_status
            name: Sonoff Status
          - entity: binary_sensor.sonoff_4ch_button_1
            name: Top Flat
          - entity: binary_sensor.sonoff_4ch_button_2
            name: Raised Bed
          - entity: binary_sensor.sonoff_4ch_button_3
            name: Slope
          - entity: binary_sensor.sonoff_4ch_button_4
            name: Water Status
      - type: light
        entity: light.sonoff_4ch_blue_led
