- alias: Notify if sonoff disconnects
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.sonoff_4ch_status
    to: 'off'
    for:
      minutes: 5
  action:
  - service: notify.mobile_app_joes_iphone
    data:
      message: Sonoff has disconnected
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: switch.turn_off
    entity_id: switch.ikea_plug_blue

- alias: Turn sonoff power back on
  trigger:
  - platform: state
    entity_id:
      - switch.ikea_plug_blue
    to: 'off'
    for:
      minutes: 2
  action:
  - service: switch.turn_on
    entity_id: switch.ikea_plug_blue

- alias: Notify if sprinklers left on for 10 minutes
  trigger:
  - platform: state
    entity_id:
      - switch.sonoff_4ch_relay_1
      - switch.sonoff_4ch_relay_2
      - switch.sonoff_4ch_relay_3
      - switch.sonoff_4ch_relay_4
      - switch.backyard_relay_1
      - switch.backyard_relay_2
    to: 'on'
    for:
      minutes: 10
  action:
  - service: notify.mobile_app_joes_iphone
    data:
      message: Sprinkler has been running for > 10 min
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: switch.turn_off
    entity_id: switch.ikea_plug_blue

# - alias: Water Frontyard Morning
#   trigger:
#     - platform: time
#       at: '04:00:00'
#   conditions:
#     - condition: template
#       value_template: "{{now().strftime('%j')|int % 2 == 0}}"
#     - condition: state
#       entity_id: "input_boolean.skip_watering"
#       state: 'off'
#     - condition: state
#       entity_id: "input_boolean.turn_off_watering"
#       state: 'off'
#   action:
#     - service: script.sprinkler_water_front

# - alias: Water Frontyard Afternoon
#   trigger:
#     - platform: time
#       at: '14:00:00'
#   conditions:
#     - condition: template
#       value_template: "{{now().strftime('%j')|int % 2 == 0}}"
#     - condition: state
#       entity_id: "input_boolean.skip_watering"
#       state: 'off'
#     - condition: state
#       entity_id: "input_boolean.turn_off_watering"
#       state: 'off'
#   action:
#     - service: script.sprinkler_water_front
