- alias: Notify if sonoff disconnects
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sonoff_4ch_status
    to: 'off'
    for:
      minutes: 5
  action:
  - service: notify.mobile_app_joes_iphone
    data:
      message: Sonoff has disconnected
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: switch.turn_off
    entity_id: switch.sonoff_power_on_off

- alias: Turn sonoff power back on
  trigger:
  - platform: state
    entity_id:
    - switch.sonoff_power_on_off
    to: 'off'
    for:
      minutes: 2
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff_power_on_off

- alias: Notify if sprinklers left on for 20 minutes
  id: c72b1caa51424d049a2f144c1160d7c7
  trigger:
  - platform: state
    entity_id:
    - switch.sonoff_4ch_relay_1
    - switch.sonoff_4ch_relay_2
    - switch.sonoff_4ch_relay_3
    - switch.sonoff_4ch_relay_4
    to: 'on'
    for:
      minutes: 20
  action:
  - service: notify.mobile_app_joes_iphone
    data:
      message: Sprinkler has been running for > 30 min
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1.0
  - service: switch.turn_off
    entity_id: switch.sonoff_power_on_off

- alias: Turn on porch at night
  trigger:
  - platform: time
    at: '19:00:00'
  action:
    entity_id: light.porch_2
    service: light.turn_on
    data:
      brightness: 10

- alias: Turn off porch at night
  trigger:
  - platform: time
    at: '00:00:00'
  action:
    entity_id: light.porch_2
    service: light.turn_off

- alias: Water Frontyard Morning
  id: d3b9ce0c8a7f4527b200174e076f9213
  trigger:
  - platform: time
    at: '04:00:00'
  action:
  - service: script.sprinkler_water_front

- alias: Water Frontyard Afternoon
  id: d5b9ce1c9a9f4528b200175e077f9213
  trigger:
  - platform: time
    at: '14:00:00'
  action:
  - service: script.sprinkler_water_front
