- alias: Turn on lights when Joe is home
  trigger:
    platform: state
    entity_id: device_tracker.joe_tracker_presence, device_tracker.kim_tracker_presence
    to: 'Just arrived'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_hue
        state: 'off'
  action:
    entity_id: light.living_room_hue
    service: light.turn_on
    data:
      brightness: 80

- alias: Turn on lights when Front Door is Opened
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_hue
        state: 'off'
  action:
    entity_id: light.living_room_hue
    service: light.turn_on
    data:
      brightness: 80
