- alias: Turn on flood light when motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.flood_light_zone
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    entity_id: light.flood_light
    service: light.turn_on
    data:
      brightness: 35

- alias: Turn off flood light when motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.flood_light_zone
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    entity_id: light.flood_light
    service: light.turn_off


- alias: Kitchen light on
  description: ''
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_occupancy
    to: 'on'
  condition: []
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_plug_left
    - service: switch.turn_on
      entity_id: switch.kitchen_plug_right

- alias: Kitchen light off
  description: ''
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_occupancy
    to: 'off'
  condition: []
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_plug_left
    - service: switch.turn_off
      entity_id: switch.kitchen_plug_right

- alias: Bella light on
  description: ''
  trigger:
    platform: state
    entity_id: binary_sensor.bella_motion_occupancy
    to: 'on'
  condition:
    - condition: time
      after: '09:00'
      before: '21:00'
  action:
    - service: light.turn_on
      entity_id: light.hue_bella_left
    - service: light.turn_on
      entity_id: light.hue_bella_right
    - service: light.turn_on
      entity_id: light.nanoleaf
  mode: single

- alias: Bella light off
  description: ''
  trigger:
    platform: state
    entity_id: binary_sensor.bella_motion_occupancy
    to: 'off'
  condition:
    - condition: time
      after: '09:00'
      before: '21:00'
  action:
    - service: light.turn_off
      entity_id: light.hue_bella_left
    - service: light.turn_off
      entity_id: light.hue_bella_right
    - service: light.turn_off
      entity_id: light.nanoleaf
  mode: single

