esphome:
  name: knob_plain
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Knob Plain Fallback Hotspot"
    password: "QdnKmoqMPiuH"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
